### PR TITLE
Bring back lost patch to bad hash resulting in exploding map

### PR DESCRIPTION
**Pull request by dabaitu**
https://github.com/twitter-forks/presto/pull/15

### CODE REVIEW

**Comment by billonahill** [comment]
Have you reproduced the problem locally and verified that this patch fixes it? We definitely want to do that before applying this (see my comments on #15). The behavior from #15 was very easy to confirm with and without that patch by running locally and attaching a debugger. That PR includes instructions.

When was the last time that this code was in place on our fork? Was that TODO comment still there? I thought we addressed that since shipping #15.

**Comment by dabaitu** [comment]
@billonahill trying to reproduce locally, but I guess you are right, this is probably not the root cause.

**Comment by dabaitu** [comment]
@billonahill https://github.com/prestodb/presto-hadoop-apache1/issues/7

**Comment by dabaitu** [comment]
I'm not able to reproduce the problem locally. I think I need to attach the debugger to our devel cluster where it has access to data with more partitions. I think there's a cache per user, and a new entry is created for every full data path the user queries, and our heavy users exceed 1000.

**Comment by billonahill** [comment]
You can see the behavior by running a single-node dev instance of heron and attaching a debugger to it. Previously when there was a leak in the cache you'd see new entries get added for every user/query/fs, which we patched to be for every user/fs.

**Comment by Yaliang** [comment]
Looks like we have resolved the problem with another config. Let's close this PR for now.

**Pull request closed without merging**
