### PR TITLE
Cache the UGI object per user in BackgroundHiveSplitLoader

### PR DESCRIPTION
**Pull request by billonahill**

### CODE REVIEW

**Comment by saileshmittal** [comment]
@billonahill shipit
Before merging, could you add some details about the problem we saw, and how this change solves it?

**Comment by billonahill** [comment]
This change patches a memory leak found when querying Hive as the user (i.e. `hive.read-as-query-user=true`).

#### Problem:
The issue is due to how [org.apache.hadoop.fs.PrestoFileSystemCache](https://github.com/prestodb/presto-hadoop-apache2/blob/master/src/main/java/org/apache/hadoop/fs/PrestoFileSystemCache.java#L56) caches `FileSystems` by a key which contains the fs scheme (e.g. hdfs), authority (e.g. cluster-name) and the `org.apache.hadoop.secturity.UserGroupInformation` (or ugi) object, which is specific to the user.

The ugi object implements the `hashCode()` method as `System.identityHashCode(subject)` ([javadoc](http://docs.oracle.com/javase/7/docs/api/java/lang/System.html#identityHashCode%28java.lang.Object%29)), which ignores the overwritten `hashCode()` method of the subject object and instead returns one based purely on the default method. This means that for every query a given user submits, their UGI will hash differently.

The result is that for every query made by a given user, N entries get added the the FS cache where N is the number of filesystem URIs supported in the hadoop configs. The cache map ultimately blows up.

#### To Reproduce:
Attach a debugger to the `PrestoFileSystemCache.getInternal(..)` method and watch the map expand as you re-issue the same query repeatedly. Also check the value of `key.ugi.hashCode()` versus `key.ugi.subject.hashCode()`. The former changes with every request for a user, where the latter doesn't.

**Comment by dabaitu** [comment]
@billonahill curious why this important change didn't go upstream.

**Comment by dabaitu** [comment]
Looks like OSS no longer support readAsQueryUser

**Comment by billonahill** [comment]
@dabaitu our patch for auth was rejected in favor of teradata's pending patch, which was a superset of auth modes including ours as one of them. I reviewed their patch and saw that they addressed it so we decided to let there's go in as the fix, at which point this patch would no longer be needed. It's possible that this is now the case, and the other issue we're seeing is something different.

**Pull request merged**
