### PR TITLE
Revert user based authorization

### PR DESCRIPTION
**Pull request by saileshmittal**
It causes huge performance degradation because of 
1. not-caching metastore data.
2. hadoop's doAs.

### CODE REVIEW

**Comment by johnynek** [comment]
What's the development process on this repo? Do you do any code reviews on the version that is deployed? If so, where do you code review?

**Comment by saileshmittal** [comment]
Generally me and @vikkyrk handle code reviews for twitter-fork's presto and hive repos as of now. I create pull request for any change that I want to merge so that it is tracked, instead of directly pushing into twitter-master.

This was a fairly straight forward revert that we discussed about. Hence did not require explicit shipit.

Would you like to do some code reviews and contribute as well? That would be great!

**Comment by johnynek** [comment]
I'm not sure I have time to help review this code, unfortunately, but I have seen many straightforward changes cause big problems, such that we never merge our own pull requests on many of the open source repos. Generally we have a team member merge it so at least there are two people who clearly sign off on the code (and no one internal objecting).

**Comment by saileshmittal** [comment]
For this PR, these were our own changes that did not work well. Hence the reverts. No upstream's code is being reverted.

**Comment by johnynek** [comment]
Okay, I assumed that the version we are running internally would be changed, and since that can impact customers I wanted to keep the bar high.

If this is just some test branch you had on the side, no problem. My comments are only about the branch we actually (eventually) deploy, tests don't need to be reviewed.

**Pull request merged**
