### PR TITLE
Parquet schema evolution on non-primitive type

### PR DESCRIPTION
**Pull request by Yaliang**
Added a lazy equals function in HiveType which only compare the catalog if the type is not primitive.
Added a configuration option for enabling the lazy schema matcher.
Includes a name based nested field mapping from #4714

### CODE REVIEW

**Comment by Yaliang** [comment]
Will build a new PR in upstream for testing.

**Comment by Yaliang** [comment]
Upstream's CI passed.
https://travis-ci.org/prestodb/presto/builds/198243778

**Comment by billonahill** [comment]
@Yaliang can we submit this to the OSS master first and develop this patch in the open? There is nothing Twitter-specific in this functionality and we should not fork from OSS for this.

**Comment by Yaliang** [comment]
Restructured commits

**Pull request closed without merging**
