### PR TITLE
Update version number to 0.210-tw-0.60

### PR DESCRIPTION
**Pull request by Yaliang**

### CODE REVIEW

**Review by dcfocus — APPROVED** [review]
Approved. Quick question, is there a way to make it a variable so that we only need to change at one place? Not familiar with Pom.

**Review by mghosh4 — APPROVED** [review]
Is this for the security configuration update?

**Comment by Yaliang** [comment]
> Is this for the security configuration update?

Yes, also include the Dynamic Page Sizing for parquet from Hao

**Comment by Yaliang** [comment]
> Approved. Quick question, is there a way to make it a variable so that we only need to change at one place? Not familiar with Pom.

Seems doable but not so good for me. https://stackoverflow.com/a/10582306

**Pull request merged**
